# Generated by Django 4.0.6 on 2022-07-29 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_remove_condition_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
