# Generated by Django 4.0.6 on 2022-07-29 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_condition_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
