# Generated by Django 4.1 on 2022-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_calorie', models.IntegerField()),
                ('target_protein', models.FloatField()),
                ('target_carbohydrate', models.FloatField()),
                ('target_lipid', models.FloatField()),
            ],
        ),
    ]
